### ISSUE TITLE
Fix Guide and Contributors 404 error page

### ISSUE THREAD

**Issue by israelmitolu** [Evavic44/portfolio-ideas#273]
It appears that on the [documentation website](https://portfolio-ideas.vercel.app/), clicking on either the Guide or Contributors link results in a 404 error page.

**Comment by Evavic44** [comment]
Thanks, @israelmitolu. This is actually a known bug and not really important to fix for now since we already have a **CONTRIBUTING** guideline and a **Contributors** section in the README.md. But in case anyone is interested in fixing this, your PR is definitely welcome. 🙂

## Solution
Create a `guide.md` and `contributors.md` files inside the docs folder.

1. For the guide, add the content of [CONTRIBUTING.md](https://github.com/Evavic44/portfolio-ideas/blob/main/CONTRIBUTING.md)
2. For the contributors, you can customize it with vue components or for simplicity, custom HTML. [Example here](https://github.com/Evavic44/adocs/blob/main/docs/index.md#).

**Comment by israelmitolu** [comment]
Alright then
